import mongoose,{Schema,Types,model} from 'mongoose';
const productSchema=new Schema({
   name:{
        type:String,
        required:true,
        unique:true,
        trim:true
    },
    slug:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
    },
    VideoPrice:{
        type:Number,
        required:true
    },
    PotoPrice:{
        type:Number,
        required:true
    },
    discount:{
     type:Number,
     default:0
    },
    finalPrice:{type:Number},
    mainImage:{
        type:Object,
        required:true,
    },
    subImages:[{type:Object,required:true}],
    status:{
        type:String,
        default:"Active",
        enum:["Active","Inactive"]
    },
    isDeleted:{type:Boolean,default:false},
    categoryId:{type:Types.ObjectId,ref:"Category",required:true},
    subcategoryId:{type:Types.ObjectId,ref:"subcategory",required:true},
    createdBy:{type:Types.ObjectId,ref:"User",required:true},
    updatedBy:{type:Types.ObjectId,ref:"User",required:true},
},
{
    timestamps:true,
    toJSON:{virtuals:true},
    toObject:{virtuals:true}
}

)
productSchema.virtual("review",{
    ref:"Review",
    localField:'_id',
    foreignField:'productId'
})
;
const productModel=mongoose.models.Product||model("Product",productSchema);
export default productModel;